### ISSUE TITLE
🐞There's bug on sign up page on the android app!

### ISSUE THREAD

**Issue by Zinoujoker** [logseq/docs#124]
theres bug on sign up page on the android app!
whene i try go to sign up page and try to put email and username and other info i cant it keep refreshing and the keyboard go down idk what's the problem 🤔 its annoying 😤 i want sign up & create new account to sync my notes .. please fix it

**Comment by xyhp915** [comment]
Hi, @Zinoujoker Thank you for your feedback; the fixed code has been submitted; if merged, you can install it through nightly APK for Android.  ▶  [Nightly releases](https://github.com/logseq/logseq/releases/tag/untagged-bc004e76344d1b1c8254)
