### ISSUE TITLE
Add document for Namespace

### ISSUE THREAD

**Issue by cnrpman** [logseq/docs#58]
Document for namespace is missing on https://github.com/logseq/docs
Supporting material:
https://github.com/logseq/logseq/issues/3214#issuecomment-1364707933

**Comment by cnrpman** [comment]
https://github.com/logseq/logseq/issues/8340

**Comment by logseq-cldwalker** [comment]
@cnrpman Fyi I've removed the label and added a TODO to the Namespaces page. I don't think you were aware but tasks in this project have been tracked for awhile with `#docs` in the app - https://docs.logseq.com/#/page/docs. Would prefer the `documentation` label is only used for external projects to make the contribution process easier to understand and review. I've explained this in https://github.com/logseq/docs/blob/master/CONTRIBUTING.md#what-to-contribute

**Comment by cnrpman** [comment]
@logseq-cldwalker I see! So I'm closing this ticket

**Comment by kerim** [comment]
Strange that documentation of this core feature is still missing?

**Comment by amithm7** [comment]
@cnrpman This issue is still linked from the missing documentation page: https://docs.logseq.com/#/page/namespaces

**Comment by codekiln** [comment]
I don't understand why this issue was closed; is the logseq project actually tracking the things that need to be done in logseq TODOs rather than in github issues?
