### ISSUE TITLE
Document for "How to track performance issues"

### ISSUE THREAD

**Issue by cnrpman** [logseq/docs#59]
It's a painful process of tracking down performance issues. For example: 
https://twitter.com/cnjunyi/status/1607056174612119553?s=20&t=-Jcq3KLOuB8UU7M_1wPpvQ
https://github.com/logseq/logseq/issues/8137

We should setup a FAQ on the forum https://discuss.logseq.com/c/faq/6 to help saving the communication cost of the process. Then make it to the document.

Some basic text pieces on the topic:
Most performance degradation happens when edited from outside, may caused by cache corruption. Try best to collect the way to reproduce the performance degradation.
To reset the cache issue, may try in following steps: Re-index. [Clear cache](https://discuss.logseq.com/t/how-to-clear-cache-in-logseq/13693/1).
A performance profile will be super helpful https://help.figma.com/hc/en-us/articles/360041468414-Record-a-Chrome-Performance-Profile
Locating the content that cause the performance issue will be very helpful

**Comment by logseq-cldwalker** [comment]
Closing as it's been almost 2 years and no interest in this
