### ISSUE TITLE
Enhancement to doc "page alias"

### ISSUE THREAD

**Issue by situ2001** [logseq/docs#68]
Thanks for the amazing docs. I find that using this feature is not always easy and straight-forward, and it may make a mess for users and confuse them. should describe the detailed behavior of the page alias so that users can be comfortable using the page alias feature.

https://docs.logseq.com/#/page/term%2Falias

For example.

1. What happens if I add an alias for a page?  (DONE)
2. What happens if the alias is used by an _empty page_?
3. What happens if the alias is used by a _non-empty page_?
4. What happens if I use page alias with namespace page?
5. What is the limitation?
6. More...

**Comment by situ2001** [comment]
> For example.

7. What happens if I rename the page name to an exist alias name?

**Comment by logseq-cldwalker** [comment]
A PR for improving alias docs would be great as there is almost nothing. https://github.com/logseq/docs/blob/master/CONTRIBUTING.md#what-to-contribute provides some guidance on what to contribute

**Comment by logseq-cldwalker** [comment]
Closing as it's been almost 2 years and no interest in this
