### ISSUE TITLE
config.edn quick capture template does not match docs

### ISSUE THREAD

**Issue by Bad3r** [logseq/docs#81]
<table><tbody><tr><td>Logseq Docs</td><td><code>config.edn</code> Template</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218299606-db178f87-b335-41c6-95af-0b02adcf7a65.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/218299704-81a478b8-e23e-4e66-86e9-942972b9cbb1.png"></figure></td></tr></tbody></table>

  
I think the config.edn template should be updated to match the example in Logseq docs.

The codeblock formatting in Docs is strange to me. It can be improved by splitting the first line to make it fit within the codeblock without needing to scroll to the right.

Also, the number of spaces used for indentation seems unnecessarily long. @logseq-cldwalker, what do you think? I can submit a PR to fix both.

Most docs-related issues will still be moved to the docs' repo. This issue is technically 2 issues.

1\. Update codeblock formatting in Logseq docs.

2\. update config.edn template to match Logseq docs.

**Comment by logseq-cldwalker** [comment]
@Bad3r No objection from me but will defer to @andelf on this since he's been developing this feature and the docs
