### ISSUE TITLE
"Make a Card" should read "Make a Flashcard" upon right click.

### ISSUE THREAD

**Issue by kokosthief** [logseq/docs#93]
"Make a Card" should read "Make a Flashcard" upon right click.
[Make a card - Docs](https://docs.logseq.com/#/page/flashcards/block/how%20to%20create%20a%20card%3F)

**Comment by logseq-cldwalker** [comment]
Hi. A pull request would be great for this. See https://github.com/logseq/docs/blob/master/CONTRIBUTING.md#how-to-contribute for more on how to do this

**Comment by kokosthief** [comment]
Nice will do!
