### ISSUE TITLE
Advanced query example with `:block/tags`

### ISSUE THREAD

**Issue by gdw2** [logseq/docs#95]
I tried the advanced query below [src here](https://github.com/logseq/docs/blob/1f96da26d01c36c1e349aacf5cc1fb4a4fbab9ce/pages/Advanced%20Queries.md?plain=1#L200) and it didn't return any results, despite having pages that have `#programming` tags.  

```clojure
	  #+BEGIN_QUERY
	  {:title "All pages have a *programming* tag"
	   :query [:find ?name
	         :in $ ?tag
	         :where
	         [?t :block/name ?tag]
	         [?p :block/tags ?t]
	         [?p :block/name ?name]]
	   :inputs ["programming"]
	   :view (fn [result]
	         [:div.flex.flex-col
	          (for [page result]
	            [:a {:href (str "#/page/" page)} (clojure.string/capitalize page)])])}
	  #+END_QUERY
```

I suspect the example is wrong, particularly the `:block/tags` part, for two reasons:

1. When I right click on a page and select the "(Dev) Show page data" option, I see the page's attributes, but I don't see a `:block/tags` attribute. 
2. When querying logseq for any blocks or pages with the `block/tags` attribute, nothing is returned.  

```clojure
#+BEGIN_QUERY
{:title "All tasks"
 :query [:find (pull ?b [*])
         :where
         [?b :block/tags _]]}
#+END_QUERY
```

Could this example be wrong? If so, how would one do this query?

**Comment by gdw2** [comment]
This seems to work for me:

```clojure
#+BEGIN_QUERY
{:title "All pages have a *programming* tag"
 :query [:find ?name
         :in $ ?tag
         :where
         [?t :block/name ?tag]
         [?b :block/refs ?t]
         [?b :block/page ?p]
         [?p :block/name ?name]]
 :inputs ["programming"]
 :view (fn [result]
       [:div.flex.flex-col
        (for [page result]
          [:a {:href (str "#/page/" page)} (clojure.string/capitalize page)])])}
#+END_QUERY
```

**Comment by logseq-cldwalker** [comment]
Hi. The documented query works for me with the following md page:
```
tags:: programming
```
The command shows :block/tags:
<img width="847" alt="Screen Shot 2023-04-20 at 10 14 47 AM" src="https://user-images.githubusercontent.com/97210743/233393807-7305de13-58b1-4d09-a8f9-f57484f679a0.png">

**Comment by gdw2** [comment]
Thanks.  

I'm relatively new to logseq and the advanced query page seems to use 'tags' to mean backlinks included in a block _as well as_ putting the tags property on a page.  I wasn't aware of the latter use.  

I'll close this issue.
